-- ============================================================================
-- VULCAN MATERIALS REVENUE FORECAST PLATFORM - Atomic Tables
-- ============================================================================
-- Core entity tables for revenue forecasting
-- Modeled after Power & Utilities atomic layer
-- ============================================================================

USE DATABASE VULCAN_MATERIALS_DB;
USE SCHEMA ATOMIC;

-- ============================================================================
-- REFERENCE TABLES
-- ============================================================================

-- Geographic Sales Regions (analog to ERCOT Load Zones)
CREATE OR REPLACE TABLE SALES_REGION (
    REGION_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    REGION_CODE VARCHAR(50) NOT NULL UNIQUE,
    REGION_NAME VARCHAR(100) NOT NULL,
    REGION_TYPE VARCHAR(50),
    PRIMARY_STATES ARRAY,
    HEADQUARTERS_CITY VARCHAR(100),
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    TOTAL_RESERVES_TONS NUMBER,
    ANNUAL_CAPACITY_TONS NUMBER,
    EMPLOYEE_COUNT NUMBER,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Seed Vulcan's primary sales regions (based on 10-K geographic segments)
INSERT INTO SALES_REGION (REGION_CODE, REGION_NAME, REGION_TYPE, PRIMARY_STATES, HEADQUARTERS_CITY, LATITUDE, LONGITUDE, TOTAL_RESERVES_TONS, ANNUAL_CAPACITY_TONS, EMPLOYEE_COUNT)
VALUES 
    ('TEXAS', 'Texas Region', 'CORE_MARKET', ARRAY_CONSTRUCT('TX'), 'Dallas', 32.7767, -96.7970, 3200000000, 55000000, 2100),
    ('SOUTHEAST', 'Southeast Region', 'CORE_MARKET', ARRAY_CONSTRUCT('GA', 'NC', 'SC', 'TN', 'AL'), 'Atlanta', 33.7490, -84.3880, 4500000000, 72000000, 3200),
    ('FLORIDA', 'Florida Region', 'STRATEGIC', ARRAY_CONSTRUCT('FL'), 'Tampa', 27.9506, -82.4572, 1200000000, 28000000, 1400),
    ('CALIFORNIA', 'California Region', 'CORE_MARKET', ARRAY_CONSTRUCT('CA', 'AZ'), 'Los Angeles', 34.0522, -118.2437, 2800000000, 42000000, 1800),
    ('VIRGINIA', 'Mid-Atlantic Region', 'GROWTH', ARRAY_CONSTRUCT('VA', 'MD', 'DC'), 'Richmond', 37.5407, -77.4360, 1800000000, 25000000, 900),
    ('ILLINOIS', 'Central Region', 'STRATEGIC', ARRAY_CONSTRUCT('IL', 'IN', 'KY'), 'Chicago', 41.8781, -87.6298, 1500000000, 18000000, 750),
    ('MEXICO', 'Mexico (SAC TUN)', 'SUSPENDED', ARRAY_CONSTRUCT('MX'), 'Quintana Roo', 20.5001, -87.4530, 500000000, 0, 50);

-- Product Segments (Aggregates, Asphalt, Concrete)
CREATE OR REPLACE TABLE PRODUCT_SEGMENT (
    SEGMENT_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    SEGMENT_CODE VARCHAR(50) NOT NULL UNIQUE,
    SEGMENT_NAME VARCHAR(100) NOT NULL,
    SEGMENT_TYPE VARCHAR(50),
    DESCRIPTION VARCHAR(500),
    AVG_PRICE_PER_TON NUMBER(10,2),
    AVG_MARGIN_PCT NUMBER(8,2),
    IS_PRIMARY_BUSINESS BOOLEAN DEFAULT FALSE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO PRODUCT_SEGMENT (SEGMENT_CODE, SEGMENT_NAME, SEGMENT_TYPE, DESCRIPTION, AVG_PRICE_PER_TON, AVG_MARGIN_PCT, IS_PRIMARY_BUSINESS)
VALUES
    ('AGG_STONE', 'Crushed Stone', 'AGGREGATES', 'Crushed limestone, granite, trap rock for construction', 21.98, 51.5, TRUE),
    ('AGG_SAND', 'Sand & Gravel', 'AGGREGATES', 'Natural sand and gravel for concrete and asphalt', 18.50, 48.0, TRUE),
    ('AGG_SPECIALTY', 'Specialty Aggregates', 'AGGREGATES', 'Railroad ballast, rip rap, armor stone', 28.50, 55.0, TRUE),
    ('ASPHALT_MIX', 'Asphalt Mix', 'ASPHALT', 'Hot mix asphalt for paving', 85.00, 12.0, FALSE),
    ('LIQUID_AC', 'Liquid Asphalt', 'ASPHALT', 'Liquid asphalt cement (purchased input)', 650.00, 8.0, FALSE),
    ('CONCRETE_RMX', 'Ready-Mix Concrete', 'CONCRETE', 'Ready-mixed concrete delivered to job site', 145.00, 15.0, FALSE);

-- Customer Segments (Public vs Private)
CREATE OR REPLACE TABLE CUSTOMER_SEGMENT (
    SEGMENT_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    SEGMENT_CODE VARCHAR(50) NOT NULL UNIQUE,
    SEGMENT_NAME VARCHAR(100) NOT NULL,
    SECTOR VARCHAR(50),
    DESCRIPTION VARCHAR(500),
    REVENUE_SHARE_PCT NUMBER(8,2),
    CYCLICALITY VARCHAR(20),
    KEY_DRIVERS ARRAY,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO CUSTOMER_SEGMENT (SEGMENT_CODE, SEGMENT_NAME, SECTOR, DESCRIPTION, REVENUE_SHARE_PCT, CYCLICALITY, KEY_DRIVERS)
VALUES
    ('PUBLIC_HIGHWAY', 'Highway & Street', 'PUBLIC', 'State DOT highway, bridge, and road projects', 35.0, 'LOW', ARRAY_CONSTRUCT('IIJA_FUNDING', 'STATE_DOT_BUDGET', 'FUEL_TAX_RECEIPTS')),
    ('PUBLIC_OTHER', 'Other Public Works', 'PUBLIC', 'Municipal water, sewer, airports, transit', 12.0, 'LOW', ARRAY_CONSTRUCT('MUNICIPAL_BUDGETS', 'FEDERAL_GRANTS')),
    ('PRIVATE_COMMERCIAL', 'Commercial/Industrial', 'PRIVATE', 'Office, retail, warehouse, data centers', 18.0, 'HIGH', ARRAY_CONSTRUCT('INTEREST_RATES', 'COMMERCIAL_PERMITS', 'DATA_CENTER_DEMAND')),
    ('PRIVATE_RESIDENTIAL', 'Residential', 'PRIVATE', 'Single-family and multi-family housing', 22.0, 'HIGH', ARRAY_CONSTRUCT('MORTGAGE_RATES', 'HOUSING_STARTS', 'POPULATION_GROWTH')),
    ('PRIVATE_INDUSTRIAL', 'Heavy Industrial', 'PRIVATE', 'Manufacturing, energy, mining facilities', 8.0, 'MEDIUM', ARRAY_CONSTRUCT('MANUFACTURING_INDEX', 'RESHORING_ACTIVITY')),
    ('OTHER', 'Other/Unclassified', 'OTHER', 'Miscellaneous and spot sales', 5.0, 'MEDIUM', ARRAY_CONSTRUCT('GDP_GROWTH'));

-- Quarry Facilities (analog to Generation Units in P&U)
CREATE OR REPLACE TABLE QUARRY_FACILITY (
    QUARRY_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    QUARRY_CODE VARCHAR(50) NOT NULL UNIQUE,
    QUARRY_NAME VARCHAR(200) NOT NULL,
    REGION_CODE VARCHAR(50) REFERENCES SALES_REGION(REGION_CODE),
    STATE VARCHAR(10),
    COUNTY VARCHAR(100),
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    ROCK_TYPE VARCHAR(100),
    PROVEN_RESERVES_TONS NUMBER,
    PROBABLE_RESERVES_TONS NUMBER,
    ANNUAL_CAPACITY_TONS NUMBER,
    RAIL_SERVED BOOLEAN DEFAULT FALSE,
    WATER_SERVED BOOLEAN DEFAULT FALSE,
    PERMIT_EXPIRY_DATE DATE,
    ACQUISITION_DATE DATE,
    STATUS VARCHAR(20) DEFAULT 'Active',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- TIME SERIES TABLES
-- ============================================================================

-- Monthly Shipments by Region/Product (analog to Hourly Load)
CREATE OR REPLACE TABLE MONTHLY_SHIPMENTS (
    SHIPMENT_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    REGION_CODE VARCHAR(50) NOT NULL,
    PRODUCT_SEGMENT_CODE VARCHAR(50) NOT NULL,
    CUSTOMER_SEGMENT_CODE VARCHAR(50),
    YEAR_MONTH DATE NOT NULL,
    SHIPMENT_TONS NUMBER(15,2) NOT NULL,
    REVENUE_USD NUMBER(15,2),
    PRICE_PER_TON NUMBER(10,4),
    DAYS_IN_MONTH NUMBER(3),
    WEATHER_IMPACT_DAYS NUMBER(3) DEFAULT 0,
    YOY_VOLUME_CHANGE_PCT NUMBER(8,2),
    DATA_SOURCE VARCHAR(50) DEFAULT 'INTERNAL',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT UK_MONTHLY_SHIPMENTS UNIQUE (REGION_CODE, PRODUCT_SEGMENT_CODE, CUSTOMER_SEGMENT_CODE, YEAR_MONTH)
);

-- Monthly Pricing by Region/Product (analog to Hourly LMP)
CREATE OR REPLACE TABLE MONTHLY_PRICING (
    PRICING_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    REGION_CODE VARCHAR(50) NOT NULL,
    PRODUCT_SEGMENT_CODE VARCHAR(50) NOT NULL,
    YEAR_MONTH DATE NOT NULL,
    FREIGHT_ADJUSTED_PRICE NUMBER(10,4) NOT NULL,
    LIST_PRICE NUMBER(10,4),
    DISCOUNT_AVG_PCT NUMBER(8,2),
    CASH_GROSS_PROFIT_PER_TON NUMBER(10,4),
    CASH_COST_PER_TON NUMBER(10,4),
    YOY_PRICE_CHANGE_PCT NUMBER(8,2),
    PRICE_INDEX NUMBER(10,4),
    DATA_SOURCE VARCHAR(50) DEFAULT 'INTERNAL',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT UK_MONTHLY_PRICING UNIQUE (REGION_CODE, PRODUCT_SEGMENT_CODE, YEAR_MONTH)
);

-- Daily Commodity Prices (Diesel, Asphalt, Cement) - analog to Fuel Prices
CREATE OR REPLACE TABLE DAILY_COMMODITY_PRICES (
    PRICE_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    PRICE_DATE DATE NOT NULL,
    DIESEL_GULF_COAST NUMBER(10,4),
    DIESEL_PADD_1 NUMBER(10,4),
    DIESEL_PADD_5 NUMBER(10,4),
    LIQUID_ASPHALT_GULF NUMBER(10,4),
    LIQUID_ASPHALT_WEST NUMBER(10,4),
    CEMENT_PPI NUMBER(10,4),
    NATURAL_GAS_HENRY_HUB NUMBER(10,4),
    STEEL_HRC NUMBER(10,4),
    COPPER_LME NUMBER(10,4),
    DATA_SOURCE VARCHAR(50) DEFAULT 'EIA',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT UK_DAILY_COMMODITY UNIQUE (PRICE_DATE)
);

-- Daily Weather by Region (construction impact)
CREATE OR REPLACE TABLE DAILY_WEATHER (
    WEATHER_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    REGION_CODE VARCHAR(50) NOT NULL,
    WEATHER_DATE DATE NOT NULL,
    TEMP_HIGH_F NUMBER(8,2),
    TEMP_LOW_F NUMBER(8,2),
    TEMP_AVG_F NUMBER(8,2),
    PRECIPITATION_IN NUMBER(8,4),
    SNOW_IN NUMBER(8,4),
    WIND_SPEED_MPH NUMBER(8,2),
    HUMIDITY_PCT NUMBER(8,2),
    IS_CONSTRUCTION_DAY BOOLEAN DEFAULT TRUE,
    WEATHER_DELAY_REASON VARCHAR(100),
    CDD NUMBER(8,2),
    HDD NUMBER(8,2),
    DATA_SOURCE VARCHAR(50) DEFAULT 'NOAA',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT UK_DAILY_WEATHER UNIQUE (REGION_CODE, WEATHER_DATE)
);

-- Quarterly Financial Metrics
CREATE OR REPLACE TABLE QUARTERLY_FINANCIALS (
    FINANCIAL_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    FISCAL_QUARTER VARCHAR(10) NOT NULL,
    FISCAL_YEAR NUMBER(4) NOT NULL,
    TOTAL_REVENUE_USD NUMBER(15,2),
    AGGREGATES_REVENUE_USD NUMBER(15,2),
    ASPHALT_REVENUE_USD NUMBER(15,2),
    CONCRETE_REVENUE_USD NUMBER(15,2),
    GROSS_PROFIT_USD NUMBER(15,2),
    ADJUSTED_EBITDA_USD NUMBER(15,2),
    EBITDA_MARGIN_PCT NUMBER(8,2),
    TOTAL_SHIPMENTS_TONS NUMBER(15,2),
    AGG_PRICE_PER_TON NUMBER(10,4),
    AGG_CASH_GROSS_PROFIT_TON NUMBER(10,4),
    CAPEX_USD NUMBER(15,2),
    FREE_CASH_FLOW_USD NUMBER(15,2),
    DATA_SOURCE VARCHAR(50) DEFAULT '10-K/10-Q',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT UK_QUARTERLY_FINANCIALS UNIQUE (FISCAL_QUARTER, FISCAL_YEAR)
);

-- ============================================================================
-- MACRO INDICATOR TABLES
-- ============================================================================

-- Monthly Economic Indicators
CREATE OR REPLACE TABLE MONTHLY_MACRO_INDICATORS (
    INDICATOR_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    YEAR_MONTH DATE NOT NULL,
    TOTAL_CONSTRUCTION_USD NUMBER(18,2),
    HIGHWAY_CONSTRUCTION_USD NUMBER(18,2),
    RESIDENTIAL_CONSTRUCTION_USD NUMBER(18,2),
    NONRES_COMMERCIAL_USD NUMBER(18,2),
    NONRES_MANUFACTURING_USD NUMBER(18,2),
    HOUSING_STARTS_UNITS NUMBER(12),
    HOUSING_PERMITS_UNITS NUMBER(12),
    MORTGAGE_RATE_30YR NUMBER(8,4),
    UNEMPLOYMENT_RATE NUMBER(8,4),
    GDP_GROWTH_PCT NUMBER(8,4),
    CPI_INDEX NUMBER(10,4),
    PPI_CONSTRUCTION NUMBER(10,4),
    DODGE_MOMENTUM_INDEX NUMBER(10,4),
    ABI_INDEX NUMBER(10,4),
    DATA_SOURCE VARCHAR(50) DEFAULT 'CENSUS/FRED',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT UK_MONTHLY_MACRO UNIQUE (YEAR_MONTH)
);

-- IIJA Funding Tracker (Infrastructure Investment and Jobs Act)
CREATE OR REPLACE TABLE IIJA_FUNDING_TRACKER (
    FUNDING_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    STATE VARCHAR(10) NOT NULL,
    REGION_CODE VARCHAR(50),
    FISCAL_YEAR NUMBER(4) NOT NULL,
    PROGRAM_NAME VARCHAR(200),
    FUNDING_CATEGORY VARCHAR(100),
    OBLIGATED_USD NUMBER(15,2),
    OUTLAYED_USD NUMBER(15,2),
    REMAINING_USD NUMBER(15,2),
    PROJECT_COUNT NUMBER,
    DATA_SOURCE VARCHAR(50) DEFAULT 'FHWA',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- EVENT TABLES
-- ============================================================================

-- Cost Spike Events (analog to Price Anomaly Events)
CREATE OR REPLACE TABLE COST_SPIKE_EVENT (
    EVENT_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    EVENT_TYPE VARCHAR(50) NOT NULL,
    COMMODITY VARCHAR(100),
    EVENT_START DATE NOT NULL,
    EVENT_END DATE,
    DURATION_DAYS NUMBER,
    PEAK_PRICE NUMBER(12,4),
    BASELINE_PRICE NUMBER(12,4),
    PRICE_CHANGE_PCT NUMBER(8,2),
    ESTIMATED_MARGIN_IMPACT_USD NUMBER(15,2),
    ROOT_CAUSE VARCHAR(500),
    GEOPOLITICAL_FACTOR BOOLEAN DEFAULT FALSE,
    SUPPLY_CHAIN_FACTOR BOOLEAN DEFAULT FALSE,
    WEATHER_FACTOR BOOLEAN DEFAULT FALSE,
    SEVERITY VARCHAR(20),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Weather Disruption Events
CREATE OR REPLACE TABLE WEATHER_DISRUPTION_EVENT (
    EVENT_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    EVENT_TYPE VARCHAR(50) NOT NULL,
    EVENT_NAME VARCHAR(200),
    REGION_CODE VARCHAR(50),
    EVENT_START DATE NOT NULL,
    EVENT_END DATE,
    DAYS_LOST NUMBER,
    ESTIMATED_VOLUME_IMPACT_TONS NUMBER(15,2),
    ESTIMATED_REVENUE_IMPACT_USD NUMBER(15,2),
    DESCRIPTION VARCHAR(2000),
    SEVERITY VARCHAR(20),
    DATA_SOURCE VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Geopolitical Risk Events (SAC TUN, tariffs, etc.)
CREATE OR REPLACE TABLE GEOPOLITICAL_RISK_EVENT (
    EVENT_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    EVENT_TYPE VARCHAR(50) NOT NULL,
    EVENT_NAME VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(2000),
    EVENT_START DATE NOT NULL,
    EVENT_END DATE,
    STATUS VARCHAR(50),
    AFFECTED_REGIONS ARRAY,
    ESTIMATED_ANNUAL_EBITDA_IMPACT_USD NUMBER(15,2),
    PROBABILITY_OF_RESOLUTION_PCT NUMBER(8,2),
    RESOLUTION_TIMELINE_MONTHS NUMBER,
    MITIGATION_STRATEGY VARCHAR(1000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Seed SAC TUN dispute
INSERT INTO GEOPOLITICAL_RISK_EVENT (EVENT_TYPE, EVENT_NAME, DESCRIPTION, EVENT_START, STATUS, AFFECTED_REGIONS, ESTIMATED_ANNUAL_EBITDA_IMPACT_USD, PROBABILITY_OF_RESOLUTION_PCT, RESOLUTION_TIMELINE_MONTHS, MITIGATION_STRATEGY)
VALUES (
    'EXPROPRIATION',
    'SAC TUN Mexico Operations Shutdown',
    'Mexican government military-backed shutdown of Calica quarry and port facility in Quintana Roo. USMCA arbitration initiated seeking $500M+ damages.',
    '2022-05-13',
    'ARBITRATION_PENDING',
    ARRAY_CONSTRUCT('FLORIDA', 'SOUTHEAST'),
    90000000,
    45.0,
    24,
    'Source replacement tons from domestic quarries; pursue USMCA arbitration; maintain facility readiness for potential restart'
);

-- ============================================================================
-- CONSTRUCTION PROJECT PIPELINE
-- ============================================================================

-- Major Project Pipeline (analog to understanding future demand)
CREATE OR REPLACE TABLE CONSTRUCTION_PROJECT_PIPELINE (
    PROJECT_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    PROJECT_NAME VARCHAR(500) NOT NULL,
    PROJECT_TYPE VARCHAR(100),
    CUSTOMER_SEGMENT_CODE VARCHAR(50),
    REGION_CODE VARCHAR(50),
    STATE VARCHAR(10),
    CITY VARCHAR(100),
    ESTIMATED_VALUE_USD NUMBER(15,2),
    ESTIMATED_AGGREGATE_TONS NUMBER(15,2),
    START_DATE_PLANNED DATE,
    END_DATE_PLANNED DATE,
    STATUS VARCHAR(50),
    FUNDING_SOURCE VARCHAR(100),
    OWNER_TYPE VARCHAR(50),
    IS_VULCAN_SUPPLIER BOOLEAN,
    WIN_PROBABILITY_PCT NUMBER(8,2),
    DATA_SOURCE VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- INDEXES (Clustering Keys for Performance)
-- ============================================================================

ALTER TABLE MONTHLY_SHIPMENTS CLUSTER BY (REGION_CODE, YEAR_MONTH);
ALTER TABLE MONTHLY_PRICING CLUSTER BY (REGION_CODE, YEAR_MONTH);
ALTER TABLE DAILY_COMMODITY_PRICES CLUSTER BY (PRICE_DATE);
ALTER TABLE DAILY_WEATHER CLUSTER BY (REGION_CODE, WEATHER_DATE);
ALTER TABLE MONTHLY_MACRO_INDICATORS CLUSTER BY (YEAR_MONTH);
