-- ============================================================================
-- VULCAN MATERIALS REVENUE FORECAST PLATFORM - Datamart Views
-- ============================================================================
-- Analytical views for dashboards and reporting
-- Pattern: Following Power & Utilities Analytics schema
-- ============================================================================

USE DATABASE VULCAN_MATERIALS_DB;
USE SCHEMA ANALYTICS;

-- ============================================================================
-- REAL-TIME STATUS VIEWS
-- ============================================================================

-- Regional Performance Dashboard View (analog to V_REALTIME_GRID_STATUS)
CREATE OR REPLACE VIEW V_REGIONAL_PERFORMANCE AS
WITH latest_shipments AS (
    SELECT 
        REGION_CODE,
        SUM(SHIPMENT_TONS) as CURRENT_MONTH_TONS,
        SUM(REVENUE_USD) as CURRENT_MONTH_REVENUE,
        AVG(PRICE_PER_TON) as AVG_PRICE_PER_TON,
        MAX(YEAR_MONTH) as LATEST_MONTH
    FROM ATOMIC.MONTHLY_SHIPMENTS
    WHERE YEAR_MONTH = DATE_TRUNC('month', CURRENT_DATE())
    GROUP BY REGION_CODE
),
prior_year AS (
    SELECT 
        REGION_CODE,
        SUM(SHIPMENT_TONS) as PY_TONS,
        SUM(REVENUE_USD) as PY_REVENUE
    FROM ATOMIC.MONTHLY_SHIPMENTS
    WHERE YEAR_MONTH = DATEADD('year', -1, DATE_TRUNC('month', CURRENT_DATE()))
    GROUP BY REGION_CODE
),
pricing AS (
    SELECT 
        REGION_CODE,
        AVG(CASH_GROSS_PROFIT_PER_TON) as CASH_GP_PER_TON,
        AVG(YOY_PRICE_CHANGE_PCT) as PRICE_CHANGE_PCT
    FROM ATOMIC.MONTHLY_PRICING
    WHERE YEAR_MONTH >= DATEADD('month', -3, CURRENT_DATE())
    GROUP BY REGION_CODE
),
weather_impact AS (
    SELECT 
        REGION_CODE,
        SUM(CASE WHEN IS_CONSTRUCTION_DAY = FALSE THEN 1 ELSE 0 END) as WEATHER_DAYS_LOST_MTD
    FROM ATOMIC.DAILY_WEATHER
    WHERE WEATHER_DATE >= DATE_TRUNC('month', CURRENT_DATE())
    GROUP BY REGION_CODE
)
SELECT 
    r.REGION_CODE,
    r.REGION_NAME,
    r.PRIMARY_STATES,
    COALESCE(ls.CURRENT_MONTH_TONS, 0) as CURRENT_MONTH_TONS,
    COALESCE(ls.CURRENT_MONTH_REVENUE, 0) as CURRENT_MONTH_REVENUE,
    COALESCE(ls.AVG_PRICE_PER_TON, 0) as AVG_PRICE_PER_TON,
    COALESCE(p.CASH_GP_PER_TON, 0) as CASH_GP_PER_TON,
    COALESCE(p.PRICE_CHANGE_PCT, 0) as YOY_PRICE_CHANGE_PCT,
    ROUND((ls.CURRENT_MONTH_TONS - py.PY_TONS) / NULLIF(py.PY_TONS, 0) * 100, 2) as YOY_VOLUME_CHANGE_PCT,
    COALESCE(w.WEATHER_DAYS_LOST_MTD, 0) as WEATHER_DAYS_LOST_MTD,
    CASE 
        WHEN p.CASH_GP_PER_TON >= 11.00 THEN 'STRONG'
        WHEN p.CASH_GP_PER_TON >= 9.50 THEN 'NORMAL'
        ELSE 'WATCH'
    END as MARGIN_STATUS,
    r.STATUS as REGION_STATUS
FROM ATOMIC.SALES_REGION r
LEFT JOIN latest_shipments ls ON r.REGION_CODE = ls.REGION_CODE
LEFT JOIN prior_year py ON r.REGION_CODE = py.REGION_CODE
LEFT JOIN pricing p ON r.REGION_CODE = p.REGION_CODE
LEFT JOIN weather_impact w ON r.REGION_CODE = w.REGION_CODE
WHERE r.IS_ACTIVE = TRUE;

-- ============================================================================
-- MORNING BRIEF DATA VIEW
-- ============================================================================

CREATE OR REPLACE VIEW V_MORNING_BRIEF_DATA AS
WITH macro_latest AS (
    SELECT *
    FROM ATOMIC.MONTHLY_MACRO_INDICATORS
    WHERE YEAR_MONTH = (SELECT MAX(YEAR_MONTH) FROM ATOMIC.MONTHLY_MACRO_INDICATORS)
),
commodity_latest AS (
    SELECT *
    FROM ATOMIC.DAILY_COMMODITY_PRICES
    WHERE PRICE_DATE = (SELECT MAX(PRICE_DATE) FROM ATOMIC.DAILY_COMMODITY_PRICES)
),
commodity_prior AS (
    SELECT *
    FROM ATOMIC.DAILY_COMMODITY_PRICES
    WHERE PRICE_DATE = (SELECT MAX(PRICE_DATE) - 7 FROM ATOMIC.DAILY_COMMODITY_PRICES)
),
recent_events AS (
    SELECT 
        'COST_SPIKE' as EVENT_CATEGORY,
        EVENT_TYPE,
        COMMODITY as EVENT_SUBJECT,
        EVENT_START,
        SEVERITY,
        PRICE_CHANGE_PCT as IMPACT_VALUE
    FROM ATOMIC.COST_SPIKE_EVENT
    WHERE EVENT_START >= DATEADD('day', -30, CURRENT_DATE())
    UNION ALL
    SELECT 
        'WEATHER' as EVENT_CATEGORY,
        EVENT_TYPE,
        REGION_CODE as EVENT_SUBJECT,
        EVENT_START,
        SEVERITY,
        DAYS_LOST as IMPACT_VALUE
    FROM ATOMIC.WEATHER_DISRUPTION_EVENT
    WHERE EVENT_START >= DATEADD('day', -30, CURRENT_DATE())
)
SELECT 
    CURRENT_DATE() as BRIEF_DATE,
    m.TOTAL_CONSTRUCTION_USD / 1e9 as TOTAL_CONSTRUCTION_B,
    m.HIGHWAY_CONSTRUCTION_USD / 1e9 as HIGHWAY_CONSTRUCTION_B,
    m.RESIDENTIAL_CONSTRUCTION_USD / 1e9 as RESIDENTIAL_CONSTRUCTION_B,
    m.HOUSING_STARTS_UNITS / 1e6 as HOUSING_STARTS_M,
    m.MORTGAGE_RATE_30YR,
    m.DODGE_MOMENTUM_INDEX,
    c.DIESEL_GULF_COAST,
    ROUND((c.DIESEL_GULF_COAST - cp.DIESEL_GULF_COAST) / NULLIF(cp.DIESEL_GULF_COAST, 0) * 100, 2) as DIESEL_WOW_CHANGE_PCT,
    c.LIQUID_ASPHALT_GULF,
    ROUND((c.LIQUID_ASPHALT_GULF - cp.LIQUID_ASPHALT_GULF) / NULLIF(cp.LIQUID_ASPHALT_GULF, 0) * 100, 2) as ASPHALT_WOW_CHANGE_PCT,
    c.CEMENT_PPI,
    (SELECT COUNT(*) FROM recent_events WHERE SEVERITY = 'HIGH') as HIGH_SEVERITY_EVENTS,
    (SELECT COUNT(*) FROM recent_events) as TOTAL_RECENT_EVENTS
FROM macro_latest m
CROSS JOIN commodity_latest c
CROSS JOIN commodity_prior cp;

-- ============================================================================
-- HIDDEN PATTERNS SUMMARY VIEW
-- ============================================================================

CREATE OR REPLACE VIEW V_HIDDEN_PATTERNS_SUMMARY AS
SELECT 
    PATTERN_ID,
    PATTERN_TYPE,
    PATTERN_NAME,
    DESCRIPTION,
    DETECTION_DATE,
    ARRAY_TO_STRING(AFFECTED_REGIONS, ', ') as AFFECTED_REGIONS,
    ARRAY_TO_STRING(AFFECTED_SEGMENTS, ', ') as AFFECTED_SEGMENTS,
    OBSERVATION_COUNT,
    ROUND(STATISTICAL_SIGNIFICANCE * 100, 2) as CONFIDENCE_PCT,
    ESTIMATED_ANNUAL_IMPACT_USD / 1e6 as ANNUAL_IMPACT_M,
    ROOT_CAUSE_HYPOTHESIS,
    RECOMMENDED_ACTION,
    STATUS,
    SEVERITY,
    DATEDIFF('day', DETECTION_DATE, CURRENT_DATE()) as DAYS_SINCE_DETECTION
FROM ML.HIDDEN_PATTERN
WHERE STATUS != 'RESOLVED'
ORDER BY 
    CASE SEVERITY WHEN 'HIGH' THEN 1 WHEN 'MEDIUM' THEN 2 ELSE 3 END,
    ESTIMATED_ANNUAL_IMPACT_USD DESC;

-- ============================================================================
-- MODEL PERFORMANCE VIEW
-- ============================================================================

CREATE OR REPLACE VIEW V_MODEL_PERFORMANCE AS
SELECT 
    mr.MODEL_ID,
    mr.MODEL_NAME,
    mr.MODEL_VERSION,
    mr.MODEL_TYPE,
    mr.TARGET_VARIABLE,
    mr.MAPE,
    mr.RMSE,
    mr.R2_SCORE,
    mr.FORECAST_HORIZON_MONTHS,
    mr.IS_ACTIVE,
    mr.DEPLOYED_AT,
    COUNT(rf.FORECAST_ID) as FORECAST_COUNT,
    AVG(bt.PERCENTAGE_ERROR) as AVG_BACKTEST_ERROR,
    SUM(CASE WHEN bt.WITHIN_95_CI THEN 1 ELSE 0 END) / NULLIF(COUNT(bt.BACKTEST_ID), 0) * 100 as CI_COVERAGE_PCT
FROM ML.MODEL_REGISTRY mr
LEFT JOIN ML.REVENUE_FORECAST rf ON mr.MODEL_ID = rf.MODEL_ID
LEFT JOIN ML.BACKTEST_RESULTS bt ON mr.MODEL_ID = bt.MODEL_ID
GROUP BY 
    mr.MODEL_ID, mr.MODEL_NAME, mr.MODEL_VERSION, mr.MODEL_TYPE,
    mr.TARGET_VARIABLE, mr.MAPE, mr.RMSE, mr.R2_SCORE,
    mr.FORECAST_HORIZON_MONTHS, mr.IS_ACTIVE, mr.DEPLOYED_AT
ORDER BY mr.IS_ACTIVE DESC, mr.DEPLOYED_AT DESC;

-- ============================================================================
-- REVENUE FORECAST SUMMARY VIEW
-- ============================================================================

CREATE OR REPLACE VIEW V_REVENUE_FORECAST_SUMMARY AS
SELECT 
    rf.FORECAST_DATE,
    rf.FORECAST_HORIZON,
    rf.REGION_CODE,
    sp.SCENARIO_NAME,
    sp.SCENARIO_TYPE,
    rf.PREDICTED_REVENUE_USD / 1e9 as PREDICTED_REVENUE_B,
    rf.PREDICTED_VOLUME_TONS / 1e6 as PREDICTED_VOLUME_M_TONS,
    rf.PREDICTED_PRICE_PER_TON,
    rf.PREDICTED_EBITDA_USD / 1e9 as PREDICTED_EBITDA_B,
    rf.PREDICTED_MARGIN_PCT,
    rf.CONFIDENCE_INTERVAL_LOW / 1e9 as CI_LOW_B,
    rf.CONFIDENCE_INTERVAL_HIGH / 1e9 as CI_HIGH_B,
    rf.PERCENTILE_5 / 1e9 as P5_B,
    rf.PERCENTILE_50 / 1e9 as P50_B,
    rf.PERCENTILE_95 / 1e9 as P95_B,
    rf.VALUE_AT_RISK_95 / 1e9 as VAR_95_B,
    rf.SIMULATION_COUNT,
    mr.MODEL_NAME,
    mr.MAPE as MODEL_MAPE
FROM ML.REVENUE_FORECAST rf
JOIN ML.SCENARIO_PARAMETERS sp ON rf.SCENARIO_ID = sp.SCENARIO_ID
JOIN ML.MODEL_REGISTRY mr ON rf.MODEL_ID = mr.MODEL_ID
ORDER BY rf.FORECAST_DATE DESC, rf.REGION_CODE;

-- ============================================================================
-- COST TREND ANALYSIS VIEW
-- ============================================================================

CREATE OR REPLACE VIEW V_COST_TREND_ANALYSIS AS
WITH daily_indexed AS (
    SELECT 
        PRICE_DATE,
        DIESEL_GULF_COAST,
        LIQUID_ASPHALT_GULF,
        CEMENT_PPI,
        NATURAL_GAS_HENRY_HUB,
        STEEL_HRC,
        AVG(DIESEL_GULF_COAST) OVER (ORDER BY PRICE_DATE ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) as DIESEL_30D_AVG,
        AVG(LIQUID_ASPHALT_GULF) OVER (ORDER BY PRICE_DATE ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) as ASPHALT_30D_AVG,
        FIRST_VALUE(DIESEL_GULF_COAST) OVER (ORDER BY PRICE_DATE) as DIESEL_BASELINE,
        FIRST_VALUE(LIQUID_ASPHALT_GULF) OVER (ORDER BY PRICE_DATE) as ASPHALT_BASELINE
    FROM ATOMIC.DAILY_COMMODITY_PRICES
    WHERE PRICE_DATE >= DATEADD('year', -2, CURRENT_DATE())
)
SELECT 
    PRICE_DATE,
    DIESEL_GULF_COAST,
    LIQUID_ASPHALT_GULF,
    CEMENT_PPI,
    NATURAL_GAS_HENRY_HUB,
    STEEL_HRC,
    DIESEL_30D_AVG,
    ASPHALT_30D_AVG,
    ROUND((DIESEL_GULF_COAST / NULLIF(DIESEL_BASELINE, 0) - 1) * 100, 2) as DIESEL_INDEX_CHG_PCT,
    ROUND((LIQUID_ASPHALT_GULF / NULLIF(ASPHALT_BASELINE, 0) - 1) * 100, 2) as ASPHALT_INDEX_CHG_PCT,
    CASE WHEN DIESEL_GULF_COAST > DIESEL_30D_AVG * 1.1 THEN TRUE ELSE FALSE END as DIESEL_ELEVATED,
    CASE WHEN LIQUID_ASPHALT_GULF > ASPHALT_30D_AVG * 1.1 THEN TRUE ELSE FALSE END as ASPHALT_ELEVATED
FROM daily_indexed
ORDER BY PRICE_DATE DESC;

-- ============================================================================
-- SEGMENT MIX ANALYSIS VIEW
-- ============================================================================

CREATE OR REPLACE VIEW V_SEGMENT_MIX_ANALYSIS AS
SELECT 
    s.YEAR_MONTH,
    s.REGION_CODE,
    cs.SEGMENT_NAME as CUSTOMER_SEGMENT,
    cs.SECTOR,
    SUM(s.SHIPMENT_TONS) as TOTAL_TONS,
    SUM(s.REVENUE_USD) as TOTAL_REVENUE,
    SUM(s.REVENUE_USD) / NULLIF(SUM(s.SHIPMENT_TONS), 0) as REALIZED_PRICE_PER_TON,
    SUM(s.SHIPMENT_TONS) / NULLIF(SUM(SUM(s.SHIPMENT_TONS)) OVER (PARTITION BY s.YEAR_MONTH, s.REGION_CODE), 0) * 100 as VOLUME_SHARE_PCT,
    SUM(s.REVENUE_USD) / NULLIF(SUM(SUM(s.REVENUE_USD)) OVER (PARTITION BY s.YEAR_MONTH, s.REGION_CODE), 0) * 100 as REVENUE_SHARE_PCT
FROM ATOMIC.MONTHLY_SHIPMENTS s
JOIN ATOMIC.CUSTOMER_SEGMENT cs ON s.CUSTOMER_SEGMENT_CODE = cs.SEGMENT_CODE
GROUP BY s.YEAR_MONTH, s.REGION_CODE, cs.SEGMENT_NAME, cs.SECTOR
ORDER BY s.YEAR_MONTH DESC, s.REGION_CODE, TOTAL_TONS DESC;

-- ============================================================================
-- WEATHER IMPACT SUMMARY VIEW
-- ============================================================================

CREATE OR REPLACE VIEW V_WEATHER_IMPACT_SUMMARY AS
WITH monthly_weather AS (
    SELECT 
        REGION_CODE,
        DATE_TRUNC('month', WEATHER_DATE) as YEAR_MONTH,
        COUNT(*) as TOTAL_DAYS,
        SUM(CASE WHEN IS_CONSTRUCTION_DAY = FALSE THEN 1 ELSE 0 END) as WEATHER_DELAY_DAYS,
        AVG(PRECIPITATION_IN) as AVG_PRECIP_IN,
        SUM(PRECIPITATION_IN) as TOTAL_PRECIP_IN,
        AVG(TEMP_AVG_F) as AVG_TEMP_F
    FROM ATOMIC.DAILY_WEATHER
    GROUP BY REGION_CODE, DATE_TRUNC('month', WEATHER_DATE)
)
SELECT 
    mw.YEAR_MONTH,
    mw.REGION_CODE,
    r.REGION_NAME,
    mw.TOTAL_DAYS,
    mw.WEATHER_DELAY_DAYS,
    mw.TOTAL_DAYS - mw.WEATHER_DELAY_DAYS as CONSTRUCTION_DAYS,
    ROUND(mw.WEATHER_DELAY_DAYS / mw.TOTAL_DAYS * 100, 1) as DELAY_PCT,
    mw.AVG_PRECIP_IN,
    mw.TOTAL_PRECIP_IN,
    mw.AVG_TEMP_F,
    CASE 
        WHEN mw.WEATHER_DELAY_DAYS > 8 THEN 'HIGH_IMPACT'
        WHEN mw.WEATHER_DELAY_DAYS > 4 THEN 'MODERATE_IMPACT'
        ELSE 'LOW_IMPACT'
    END as WEATHER_IMPACT_CATEGORY
FROM monthly_weather mw
JOIN ATOMIC.SALES_REGION r ON mw.REGION_CODE = r.REGION_CODE
ORDER BY mw.YEAR_MONTH DESC, mw.REGION_CODE;

-- ============================================================================
-- GEOPOLITICAL RISK DASHBOARD VIEW
-- ============================================================================

CREATE OR REPLACE VIEW V_GEOPOLITICAL_RISK_DASHBOARD AS
SELECT 
    EVENT_ID,
    EVENT_TYPE,
    EVENT_NAME,
    DESCRIPTION,
    EVENT_START,
    EVENT_END,
    DATEDIFF('day', EVENT_START, COALESCE(EVENT_END, CURRENT_DATE())) as DURATION_DAYS,
    STATUS,
    ARRAY_TO_STRING(AFFECTED_REGIONS, ', ') as AFFECTED_REGIONS,
    ESTIMATED_ANNUAL_EBITDA_IMPACT_USD / 1e6 as ANNUAL_EBITDA_IMPACT_M,
    PROBABILITY_OF_RESOLUTION_PCT,
    RESOLUTION_TIMELINE_MONTHS,
    MITIGATION_STRATEGY,
    CASE 
        WHEN STATUS = 'RESOLVED' THEN 'GREEN'
        WHEN PROBABILITY_OF_RESOLUTION_PCT >= 60 THEN 'YELLOW'
        ELSE 'RED'
    END as RISK_STATUS_COLOR
FROM ATOMIC.GEOPOLITICAL_RISK_EVENT
ORDER BY ESTIMATED_ANNUAL_EBITDA_IMPACT_USD DESC;
