-- ============================================================================
-- Vulcan Materials Revenue Forecast - Integrated Analytics Views
-- ============================================================================
-- Views that link shipments, macro (Census), and energy (Yes Energy) data
-- ============================================================================

USE DATABASE VULCAN_MATERIALS_DB;
USE SCHEMA ANALYTICS;

-- ============================================
-- REVENUE_DRIVERS_INTEGRATED
-- Links: Shipments + Macro (Census) + Energy (Yes Energy)
-- ============================================
CREATE OR REPLACE VIEW ANALYTICS.REVENUE_DRIVERS_INTEGRATED AS
WITH monthly_shipments AS (
    SELECT 
        DATE_TRUNC('month', YEAR_MONTH) AS YEAR_MONTH,
        SUM(SHIPMENT_TONS) AS TOTAL_SHIPMENTS,
        SUM(REVENUE_USD) AS TOTAL_REVENUE,
        AVG(PRICE_PER_TON) AS AVG_PRICE_PER_TON
    FROM VULCAN_MATERIALS_DB.ATOMIC.MONTHLY_SHIPMENTS
    GROUP BY DATE_TRUNC('month', YEAR_MONTH)
),
monthly_energy AS (
    SELECT 
        DATE_TRUNC('month', PRICE_DATE) AS YEAR_MONTH,
        AVG(NATURAL_GAS_HENRY_HUB) AS AVG_GAS_PRICE,
        AVG(DIESEL_GULF_COAST) AS AVG_DIESEL_PRICE,
        MIN(NATURAL_GAS_HENRY_HUB) AS MIN_GAS_PRICE,
        MAX(NATURAL_GAS_HENRY_HUB) AS MAX_GAS_PRICE,
        STDDEV(NATURAL_GAS_HENRY_HUB) AS GAS_VOLATILITY
    FROM VULCAN_MATERIALS_DB.ATOMIC.DAILY_COMMODITY_PRICES
    WHERE NATURAL_GAS_HENRY_HUB IS NOT NULL
    GROUP BY DATE_TRUNC('month', PRICE_DATE)
)
SELECT 
    s.YEAR_MONTH,
    s.TOTAL_SHIPMENTS,
    s.TOTAL_REVENUE,
    s.AVG_PRICE_PER_TON,
    m.HIGHWAY_CONSTRUCTION_USD,
    m.RESIDENTIAL_CONSTRUCTION_USD,
    m.HIGHWAY_YOY_GROWTH,
    m.RESIDENTIAL_YOY_GROWTH,
    m.CONSTRUCTION_MOMENTUM_3M,
    e.AVG_GAS_PRICE,
    e.AVG_DIESEL_PRICE,
    e.GAS_VOLATILITY,
    LAG(m.HIGHWAY_YOY_GROWTH, 3) OVER (ORDER BY s.YEAR_MONTH) AS HIGHWAY_GROWTH_LAG3M,
    LAG(e.AVG_GAS_PRICE, 1) OVER (ORDER BY s.YEAR_MONTH) AS GAS_PRICE_LAG1M,
    (s.TOTAL_REVENUE - LAG(s.TOTAL_REVENUE, 12) OVER (ORDER BY s.YEAR_MONTH)) 
        / NULLIF(LAG(s.TOTAL_REVENUE, 12) OVER (ORDER BY s.YEAR_MONTH), 0) AS REVENUE_YOY_GROWTH,
    CASE WHEN m.HIGHWAY_CONSTRUCTION_USD IS NOT NULL THEN TRUE ELSE FALSE END AS HAS_MACRO_DATA,
    CASE WHEN e.AVG_GAS_PRICE IS NOT NULL THEN TRUE ELSE FALSE END AS HAS_ENERGY_DATA
FROM monthly_shipments s
LEFT JOIN VULCAN_MATERIALS_DB.ML.FEATURE_MACRO_MONTHLY m ON s.YEAR_MONTH = m.YEAR_MONTH
LEFT JOIN monthly_energy e ON s.YEAR_MONTH = e.YEAR_MONTH
ORDER BY s.YEAR_MONTH;

-- ============================================
-- SCENARIO_SIMULATION_SUMMARY
-- Links: Scenarios + Latest Simulation Results
-- ============================================
CREATE OR REPLACE VIEW ANALYTICS.SCENARIO_SIMULATION_SUMMARY AS
SELECT 
    sd.SCENARIO_ID,
    sd.SCENARIO_NAME,
    sd.DESCRIPTION,
    sd.CATEGORY,
    sd.REVENUE_MULTIPLIER,
    sd.MARGIN_IMPACT,
    sd.DURATION_MONTHS,
    sd.DRIVERS,
    sd.GAS_PRICE_THRESHOLD,
    sd.HIGHWAY_GROWTH_THRESHOLD,
    sd.RESIDENTIAL_GROWTH_THRESHOLD,
    sd.HAS_PHASES,
    sd.COLOR,
    sd.ICON,
    sd.PROBABILITY,
    sr.RUN_ID AS LATEST_RUN_ID,
    sr.RUN_TIMESTAMP AS LATEST_RUN_TIMESTAMP,
    sr.N_PATHS,
    sr.N_MONTHS,
    sr.MODEL_TYPE,
    res.TERMINAL_MEAN,
    res.TERMINAL_VAR_95,
    res.TERMINAL_CVAR_95,
    res.CUMULATIVE_MEAN,
    res.TERMINAL_SKEWNESS,
    res.TERMINAL_KURTOSIS
FROM VULCAN_MATERIALS_DB.ML.SCENARIO_DEFINITIONS sd
LEFT JOIN (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY SCENARIO_ID ORDER BY RUN_TIMESTAMP DESC) AS rn
    FROM VULCAN_MATERIALS_DB.ML.SIMULATION_RUNS
) sr ON sd.SCENARIO_ID = sr.SCENARIO_ID AND sr.rn = 1
LEFT JOIN VULCAN_MATERIALS_DB.ML.SIMULATION_RESULTS res ON sr.RUN_ID = res.RUN_ID;

-- ============================================
-- ENERGY_MACRO_CORRELATION
-- Links: Yes Energy prices + Census construction spending
-- ============================================
CREATE OR REPLACE VIEW ANALYTICS.ENERGY_MACRO_CORRELATION AS
WITH monthly_data AS (
    SELECT 
        m.YEAR_MONTH,
        m.HIGHWAY_CONSTRUCTION_USD,
        m.RESIDENTIAL_CONSTRUCTION_USD,
        m.HIGHWAY_YOY_GROWTH,
        m.RESIDENTIAL_YOY_GROWTH,
        m.CONSTRUCTION_MOMENTUM_3M,
        AVG(c.NATURAL_GAS_HENRY_HUB) AS AVG_GAS_PRICE,
        AVG(c.DIESEL_GULF_COAST) AS AVG_DIESEL_PRICE
    FROM VULCAN_MATERIALS_DB.ML.FEATURE_MACRO_MONTHLY m
    LEFT JOIN VULCAN_MATERIALS_DB.ATOMIC.DAILY_COMMODITY_PRICES c 
        ON DATE_TRUNC('month', c.PRICE_DATE) = m.YEAR_MONTH
    GROUP BY m.YEAR_MONTH, m.HIGHWAY_CONSTRUCTION_USD, m.RESIDENTIAL_CONSTRUCTION_USD,
             m.HIGHWAY_YOY_GROWTH, m.RESIDENTIAL_YOY_GROWTH, m.CONSTRUCTION_MOMENTUM_3M
)
SELECT 
    YEAR_MONTH,
    HIGHWAY_CONSTRUCTION_USD / 1e9 AS HIGHWAY_CONSTRUCTION_B,
    RESIDENTIAL_CONSTRUCTION_USD / 1e9 AS RESIDENTIAL_CONSTRUCTION_B,
    HIGHWAY_YOY_GROWTH,
    RESIDENTIAL_YOY_GROWTH,
    CONSTRUCTION_MOMENTUM_3M,
    AVG_GAS_PRICE,
    AVG_DIESEL_PRICE,
    CASE 
        WHEN AVG_GAS_PRICE < 3.0 THEN 'ENERGY_TAILWIND'
        WHEN AVG_GAS_PRICE > 6.0 THEN 'ENERGY_SQUEEZE'
        ELSE 'NEUTRAL'
    END AS GAS_SCENARIO_SIGNAL,
    CASE 
        WHEN HIGHWAY_YOY_GROWTH > 0.15 THEN 'INFRASTRUCTURE_BOOM'
        WHEN HIGHWAY_YOY_GROWTH < -0.10 THEN 'INFRASTRUCTURE_SLOWDOWN'
        ELSE 'NEUTRAL'
    END AS HIGHWAY_SCENARIO_SIGNAL,
    CASE 
        WHEN RESIDENTIAL_YOY_GROWTH > 0.12 THEN 'HOUSING_RECOVERY'
        WHEN RESIDENTIAL_YOY_GROWTH < -0.15 THEN 'HOUSING_SLOWDOWN'
        WHEN RESIDENTIAL_YOY_GROWTH < -0.35 THEN 'HOUSING_CRASH'
        ELSE 'NEUTRAL'
    END AS RESIDENTIAL_SCENARIO_SIGNAL
FROM monthly_data
ORDER BY YEAR_MONTH DESC;

-- ============================================
-- SCENARIO_TRIGGERS
-- Shows which scenarios are triggered by current market conditions
-- ============================================
CREATE OR REPLACE VIEW ANALYTICS.SCENARIO_TRIGGERS AS
WITH current_conditions AS (
    SELECT 
        (SELECT AVG(NATURAL_GAS_HENRY_HUB) 
         FROM VULCAN_MATERIALS_DB.ATOMIC.DAILY_COMMODITY_PRICES 
         WHERE PRICE_DATE >= DATEADD('day', -30, CURRENT_DATE())) AS avg_gas_price_30d,
        (SELECT HIGHWAY_YOY_GROWTH 
         FROM VULCAN_MATERIALS_DB.ML.FEATURE_MACRO_MONTHLY 
         ORDER BY YEAR_MONTH DESC LIMIT 1) AS latest_highway_growth,
        (SELECT RESIDENTIAL_YOY_GROWTH 
         FROM VULCAN_MATERIALS_DB.ML.FEATURE_MACRO_MONTHLY 
         ORDER BY YEAR_MONTH DESC LIMIT 1) AS latest_residential_growth
)
SELECT 
    sd.SCENARIO_ID,
    sd.SCENARIO_NAME,
    sd.CATEGORY,
    sd.COLOR,
    sd.REVENUE_MULTIPLIER,
    sd.MARGIN_IMPACT,
    CASE
        WHEN sd.GAS_PRICE_THRESHOLD IS NOT NULL THEN 'GAS_PRICE'
        WHEN sd.HIGHWAY_GROWTH_THRESHOLD IS NOT NULL THEN 'HIGHWAY_GROWTH'
        WHEN sd.RESIDENTIAL_GROWTH_THRESHOLD IS NOT NULL THEN 'RESIDENTIAL_GROWTH'
        ELSE 'MANUAL'
    END AS TRIGGER_TYPE,
    cc.avg_gas_price_30d AS CURRENT_GAS_PRICE,
    cc.latest_highway_growth AS CURRENT_HIGHWAY_GROWTH,
    cc.latest_residential_growth AS CURRENT_RESIDENTIAL_GROWTH,
    sd.GAS_PRICE_THRESHOLD,
    sd.HIGHWAY_GROWTH_THRESHOLD,
    sd.RESIDENTIAL_GROWTH_THRESHOLD,
    CASE
        WHEN sd.GAS_PRICE_THRESHOLD IS NOT NULL AND cc.avg_gas_price_30d < sd.GAS_PRICE_THRESHOLD AND sd.CATEGORY = 'bull' THEN TRUE
        WHEN sd.GAS_PRICE_THRESHOLD IS NOT NULL AND cc.avg_gas_price_30d > sd.GAS_PRICE_THRESHOLD AND sd.CATEGORY IN ('bear', 'stress') THEN TRUE
        WHEN sd.HIGHWAY_GROWTH_THRESHOLD IS NOT NULL AND cc.latest_highway_growth > sd.HIGHWAY_GROWTH_THRESHOLD THEN TRUE
        WHEN sd.RESIDENTIAL_GROWTH_THRESHOLD IS NOT NULL AND cc.latest_residential_growth > sd.RESIDENTIAL_GROWTH_THRESHOLD AND sd.CATEGORY = 'bull' THEN TRUE
        WHEN sd.RESIDENTIAL_GROWTH_THRESHOLD IS NOT NULL AND cc.latest_residential_growth < sd.RESIDENTIAL_GROWTH_THRESHOLD AND sd.CATEGORY IN ('bear', 'stress') THEN TRUE
        ELSE FALSE
    END AS IS_TRIGGERED
FROM VULCAN_MATERIALS_DB.ML.SCENARIO_DEFINITIONS sd
CROSS JOIN current_conditions cc;

-- ============================================
-- REGIONAL_PERFORMANCE
-- Regional breakdown with segment mix
-- ============================================
CREATE OR REPLACE VIEW ANALYTICS.REGIONAL_PERFORMANCE AS
SELECT 
    s.REGION_CODE,
    r.REGION_NAME,
    DATE_TRUNC('quarter', s.YEAR_MONTH) AS QUARTER,
    SUM(s.SHIPMENT_TONS) AS TOTAL_TONS,
    SUM(s.REVENUE_USD) AS TOTAL_REVENUE,
    AVG(s.PRICE_PER_TON) AS AVG_PRICE_PER_TON,
    SUM(CASE WHEN s.PRODUCT_SEGMENT_CODE = 'AGG_STONE' THEN s.REVENUE_USD ELSE 0 END) AS AGG_STONE_REVENUE,
    SUM(CASE WHEN s.PRODUCT_SEGMENT_CODE = 'AGG_SAND' THEN s.REVENUE_USD ELSE 0 END) AS AGG_SAND_REVENUE,
    SUM(CASE WHEN s.PRODUCT_SEGMENT_CODE = 'ASPHALT_MIX' THEN s.REVENUE_USD ELSE 0 END) AS ASPHALT_MIX_REVENUE,
    SUM(CASE WHEN s.PRODUCT_SEGMENT_CODE = 'CONCRETE_RMX' THEN s.REVENUE_USD ELSE 0 END) AS CONCRETE_RMX_REVENUE,
    MAX(r.ANNUAL_CAPACITY_TONS) AS ANNUAL_CAPACITY,
    MAX(r.TOTAL_RESERVES_TONS) AS TOTAL_RESERVES,
    SUM(s.SHIPMENT_TONS) * 4 / NULLIF(MAX(r.ANNUAL_CAPACITY_TONS), 0) AS CAPACITY_UTILIZATION
FROM VULCAN_MATERIALS_DB.ATOMIC.MONTHLY_SHIPMENTS s
LEFT JOIN VULCAN_MATERIALS_DB.ATOMIC.SALES_REGION r ON s.REGION_CODE = r.REGION_CODE
GROUP BY s.REGION_CODE, r.REGION_NAME, DATE_TRUNC('quarter', s.YEAR_MONTH)
ORDER BY QUARTER DESC, TOTAL_REVENUE DESC;
