-- ============================================================================
-- GRANITE v2: Feature Store Supporting Tables
-- ============================================================================
-- ADDITIVE ONLY: Creates new tables in ML schema for Feature Store outputs.
-- Does NOT modify or drop any V1 tables (SCENARIO_DEFINITIONS, SIMULATION_RUNS,
-- SIMULATION_RESULTS, SENSITIVITY_ANALYSIS, FEATURE_SHIPMENT_LAGS, etc.)
-- ============================================================================

USE DATABASE VULCAN_MATERIALS_DB;
USE SCHEMA ML;

-- ============================================================================
-- ELASTICITY MODEL OUTPUTS
-- ============================================================================

CREATE TABLE IF NOT EXISTS ML.PRICE_ELASTICITY (
    ELASTICITY_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    PRODUCT_SEGMENT_CODE VARCHAR(50) NOT NULL,
    REGION_CODE VARCHAR(50),
    OWN_ELASTICITY FLOAT NOT NULL,
    STANDARD_ERROR FLOAT,
    T_STATISTIC FLOAT,
    P_VALUE FLOAT,
    R_SQUARED FLOAT,
    ADJ_R_SQUARED FLOAT,
    N_OBSERVATIONS NUMBER,
    ESTIMATION_METHOD VARCHAR(50) DEFAULT 'OLS',
    TRAINING_START_DATE DATE,
    TRAINING_END_DATE DATE,
    MODEL_VERSION VARCHAR(20) DEFAULT 'v1',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT UK_PRICE_ELASTICITY UNIQUE (PRODUCT_SEGMENT_CODE, REGION_CODE, MODEL_VERSION)
);

CREATE TABLE IF NOT EXISTS ML.ELASTICITY_MATRIX (
    MATRIX_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    PRODUCT_I VARCHAR(50) NOT NULL,
    PRODUCT_J VARCHAR(50) NOT NULL,
    CROSS_ELASTICITY FLOAT NOT NULL,
    STANDARD_ERROR FLOAT,
    T_STATISTIC FLOAT,
    P_VALUE FLOAT,
    RELATIONSHIP_TYPE VARCHAR(20),
    ESTIMATION_METHOD VARCHAR(50) DEFAULT 'SUR',
    MODEL_VERSION VARCHAR(20) DEFAULT 'v1',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT UK_ELASTICITY_MATRIX UNIQUE (PRODUCT_I, PRODUCT_J, MODEL_VERSION)
);

-- ============================================================================
-- PRICING OPTIMIZER OUTPUTS
-- ============================================================================

CREATE TABLE IF NOT EXISTS ML.OPTIMAL_PRICING (
    PRICING_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    REGION_CODE VARCHAR(50) NOT NULL,
    PRODUCT_SEGMENT_CODE VARCHAR(50) NOT NULL,
    CURRENT_PRICE FLOAT,
    OPTIMAL_PRICE FLOAT,
    PRICE_DELTA_PCT FLOAT,
    CURRENT_VOLUME FLOAT,
    PREDICTED_VOLUME FLOAT,
    VOLUME_DELTA_PCT FLOAT,
    CURRENT_PROFIT FLOAT,
    OPTIMAL_PROFIT FLOAT,
    PROFIT_DELTA FLOAT,
    PROFIT_DELTA_PCT FLOAT,
    BINDING_CONSTRAINTS VARIANT,
    MARGIN_FLOOR_USED FLOAT,
    PRICE_CHANGE_LIMIT FLOAT,
    OPTIMIZER_STATUS VARCHAR(50),
    MODEL_VERSION VARCHAR(20) DEFAULT 'v1',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- DEMAND FORECAST OUTPUTS
-- ============================================================================

CREATE TABLE IF NOT EXISTS ML.DEMAND_FORECAST (
    FORECAST_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    REGION_CODE VARCHAR(50) NOT NULL,
    PRODUCT_SEGMENT_CODE VARCHAR(50) NOT NULL,
    FORECAST_MONTH DATE NOT NULL,
    VOLUME_P10 FLOAT,
    VOLUME_P50 FLOAT,
    VOLUME_P90 FLOAT,
    REVENUE_P10 FLOAT,
    REVENUE_P50 FLOAT,
    REVENUE_P90 FLOAT,
    PRICE_ASSUMPTION FLOAT,
    SCENARIO_ID VARCHAR(50),
    MODEL_VERSION VARCHAR(20) DEFAULT 'v1',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- COPULA MODEL OUTPUTS
-- ============================================================================

CREATE TABLE IF NOT EXISTS ML.COPULA_PARAMETERS (
    PARAM_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    COPULA_TYPE VARCHAR(50) NOT NULL,
    DEGREES_OF_FREEDOM FLOAT,
    CORRELATION_MATRIX VARIANT,
    TAIL_DEPENDENCE_LOWER FLOAT,
    TAIL_DEPENDENCE_UPPER FLOAT,
    AIC FLOAT,
    BIC FLOAT,
    VARIABLES ARRAY,
    MARGINAL_PARAMS VARIANT,
    TRAINING_START_DATE DATE,
    TRAINING_END_DATE DATE,
    N_OBSERVATIONS NUMBER,
    MODEL_VERSION VARCHAR(20) DEFAULT 'v1',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS ML.MODEL_COMPARISON (
    COMPARISON_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    SCENARIO_ID VARCHAR(50),
    NAIVE_P50 FLOAT,
    NAIVE_P10 FLOAT,
    NAIVE_VAR_95 FLOAT,
    NAIVE_CVAR_95 FLOAT,
    NAIVE_PROB_MISS FLOAT,
    COPULA_P50 FLOAT,
    COPULA_P10 FLOAT,
    COPULA_VAR_95 FLOAT,
    COPULA_CVAR_95 FLOAT,
    COPULA_PROB_MISS FLOAT,
    VAR_GAP_PCT FLOAT,
    CVAR_GAP_PCT FLOAT,
    N_PATHS NUMBER,
    N_MONTHS NUMBER,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- ADD MODEL_TYPE TO EXISTING SIMULATION_RESULTS (V1 COMPATIBLE)
-- ============================================================================
-- Only adds if column doesn't already exist; safe to rerun

ALTER TABLE ML.SIMULATION_RESULTS ADD COLUMN IF NOT EXISTS MODEL_TYPE VARCHAR(20) DEFAULT 'naive';
ALTER TABLE ML.SIMULATION_RUNS ADD COLUMN IF NOT EXISTS COPULA_TYPE VARCHAR(50);

-- ============================================================================
-- ADD PRICE/VOLUME DECOMPOSITION TO EXISTING REVENUE_FORECAST (V1)
-- ============================================================================
-- Note: REVENUE_FORECAST may not exist in live Snowflake (it's in DDL 003 but
-- uses CREATE OR REPLACE pattern). Only attempt ALTER IF the table exists.
-- These are safe IF NOT EXISTS additions.

-- (REVENUE_FORECAST from 003 was CREATE OR REPLACE — may have been overwritten.
--  We skip ALTER here; the Feature Store will populate DEMAND_FORECAST instead.)
