-- ============================================================================
-- GRANITE v2: Product Line Expansion
-- ============================================================================
-- V2 ADDITIVE ONLY: Adds new product segments and shipment data for
-- ASPHALT_MIX, CONCRETE_RMX, and SERVICE_LOGISTICS.
--
-- V1 had only 3 aggregate products in MONTHLY_SHIPMENTS (AGG_STONE, AGG_SAND,
-- AGG_SPECIALTY). Vulcan Materials actually reports 4 business segments:
--   - Aggregates (~74% of revenue): Stone, Sand & Gravel, Specialty
--   - Asphalt (~15%): Hot mix asphalt
--   - Concrete (~10%): Ready-mix concrete
--   - Service (~4%): Trucking, rail, marine logistics
--
-- This DDL adds the SERVICE_LOGISTICS product to the reference table
-- (ASPHALT_MIX and CONCRETE_RMX already exist). Shipment data is generated
-- by the companion script: scripts/generate_v2_product_data.py
--
-- DOES NOT modify any V1 rows. DOES NOT use CREATE OR REPLACE on any
-- existing table. All operations are INSERT IF NOT EXISTS or additive.
-- ============================================================================

USE DATABASE VULCAN_MATERIALS_DB;
USE SCHEMA ATOMIC;

-- ============================================================================
-- 1. Add SERVICE_LOGISTICS to PRODUCT_SEGMENT (if not already present)
-- ============================================================================

INSERT INTO PRODUCT_SEGMENT (SEGMENT_CODE, SEGMENT_NAME, SEGMENT_TYPE, DESCRIPTION, AVG_PRICE_PER_TON, AVG_MARGIN_PCT, IS_PRIMARY_BUSINESS)
SELECT 'SERVICE_LOGISTICS', 'Service & Logistics', 'SERVICE',
       'Trucking, rail distribution, marine transport of aggregates and finished products',
       15.00, 25.00, FALSE
WHERE NOT EXISTS (
    SELECT 1 FROM PRODUCT_SEGMENT WHERE SEGMENT_CODE = 'SERVICE_LOGISTICS'
);

-- ============================================================================
-- 2. Update ASPHALT_MIX description to match 10-K language (safe update)
-- ============================================================================

UPDATE PRODUCT_SEGMENT
SET DESCRIPTION = 'Hot mix asphalt for road paving and construction',
    AVG_PRICE_PER_TON = 85.00,
    AVG_MARGIN_PCT = 12.00
WHERE SEGMENT_CODE = 'ASPHALT_MIX';

-- ============================================================================
-- 3. Update CONCRETE_RMX description to match 10-K language (safe update)
-- ============================================================================

UPDATE PRODUCT_SEGMENT
SET DESCRIPTION = 'Ready-mixed concrete delivered to job sites',
    AVG_PRICE_PER_TON = 145.00,
    AVG_MARGIN_PCT = 15.00
WHERE SEGMENT_CODE = 'CONCRETE_RMX';

-- ============================================================================
-- NOTE: Shipment data for ASPHALT_MIX, CONCRETE_RMX, and SERVICE_LOGISTICS
-- is generated by: scripts/generate_v2_product_data.py
-- 
-- That script creates ~1,332 new rows (3 products x 6 regions x 74 months)
-- calibrated to Vulcan's real revenue ratios from 10-K filings:
--   Asphalt: ~$1.3B annual revenue, $85/ton, seasonal (near-zero in winter)
--   Concrete: ~$0.85B annual revenue, $145/ton, moderate seasonality
--   Service: ~$0.31B annual revenue, $15/ton-equivalent, stable year-round
-- ============================================================================
