-- ============================================================================
-- WORKSTREAM C: COMPETITOR DATA INTEGRATION
-- ============================================================================
-- Creates views over Cybersyn SEC data for competitor intelligence
-- and MSHA quarry site data table
-- ============================================================================

USE DATABASE VULCAN_MATERIALS_DB;
USE SCHEMA ATOMIC;

-- ============================================================================
-- COMPETITOR FINANCIALS VIEW (Cybersyn SEC XBRL data)
-- Already exists in FEATURE_STORE as COMPETITOR_FEATURES$1; this adds
-- the full-detail ATOMIC view for ad-hoc queries and the agent.
-- ============================================================================

CREATE OR REPLACE VIEW VULCAN_MATERIALS_DB.ATOMIC.COMPETITOR_FINANCIALS AS
SELECT mt.COMPANY_NAME, mt.CIK, mt.VARIABLE_NAME, mt.TAG, mt.VALUE, mt.UNIT,
       mt.BUSINESS_SEGMENT, mt.GEO_NAME, mt.FISCAL_PERIOD, mt.FISCAL_YEAR,
       mt.PERIOD_START_DATE, mt.PERIOD_END_DATE
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.SEC_METRICS_TIMESERIES mt
WHERE mt.CIK IN ('0001396009','0000916076','0000849395','0000918646','0001571371')
  AND LOWER(mt.VARIABLE_NAME) LIKE '%revenue%';

-- ============================================================================
-- SIC PEER UNIVERSE (all SEC filers in SIC 14xx — mining/quarrying)
-- ============================================================================

CREATE OR REPLACE VIEW VULCAN_MATERIALS_DB.ATOMIC.SIC_PEERS AS
SELECT CIK, COMPANY_NAME, SIC, SIC_CODE_DESCRIPTION, STATE, CITY
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.SEC_CIK_INDEX
WHERE SIC LIKE '14%';

-- ============================================================================
-- MSHA QUARRY SITES TABLE (loaded from MSHA Open Government Data)
-- Source: https://arlweb.msha.gov/OpenGovernmentData/DataSets/Mines.zip
-- Filtered to: Active/Intermittent, Stone (canvass 6) and Sand & Gravel (5)
-- ============================================================================

CREATE TABLE IF NOT EXISTS VULCAN_MATERIALS_DB.ATOMIC.MSHA_QUARRY_SITES (
    MINE_ID VARCHAR(10),
    MINE_NAME VARCHAR(200),
    MINE_TYPE VARCHAR(50),
    MINE_STATUS VARCHAR(50),
    OPERATOR_NAME VARCHAR(200),
    OPERATOR_GROUP VARCHAR(50),
    CONTROLLER_NAME VARCHAR(200),
    STATE VARCHAR(5),
    COUNTY VARCHAR(100),
    LATITUDE NUMBER(10,7),
    LONGITUDE NUMBER(11,7),
    REGION_CODE VARCHAR(20),
    PRIMARY_SIC VARCHAR(100),
    PRIMARY_CANVASS VARCHAR(20),
    NO_EMPLOYEES NUMBER(10,0),
    NEAREST_TOWN VARCHAR(100),
    DATA_SOURCE VARCHAR(20) DEFAULT 'MSHA'
);

-- ============================================================================
-- ANALYTICS VIEWS
-- ============================================================================

USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW VULCAN_MATERIALS_DB.ANALYTICS.COMPETITIVE_LANDSCAPE AS
WITH latest_revenue AS (
    SELECT
        cf.COMPANY_NAME, cf.CIK, cf.FISCAL_YEAR, cf.FISCAL_PERIOD,
        cf.PEER_REVENUE, cf.PEER_OPERATING_INCOME, cf.PEER_MARGIN_EST,
        ROW_NUMBER() OVER (PARTITION BY cf.CIK ORDER BY cf.PERIOD_END_DATE DESC) as RN
    FROM VULCAN_MATERIALS_DB.FEATURE_STORE."COMPETITOR_FEATURES$1" cf
    WHERE cf.PEER_REVENUE IS NOT NULL
),
quarry_counts AS (
    SELECT OPERATOR_GROUP, COUNT(*) as SITE_COUNT,
           SUM(NO_EMPLOYEES) as TOTAL_EMPLOYEES,
           COUNT(DISTINCT STATE) as STATES_PRESENT
    FROM VULCAN_MATERIALS_DB.ATOMIC.MSHA_QUARRY_SITES
    WHERE OPERATOR_GROUP != 'OTHER'
    GROUP BY OPERATOR_GROUP
)
SELECT
    lr.COMPANY_NAME, lr.CIK, lr.FISCAL_YEAR, lr.FISCAL_PERIOD,
    lr.PEER_REVENUE, lr.PEER_OPERATING_INCOME, lr.PEER_MARGIN_EST,
    qc.SITE_COUNT as MSHA_QUARRY_SITES, qc.TOTAL_EMPLOYEES as MSHA_EMPLOYEES,
    qc.STATES_PRESENT,
    lr.PEER_REVENUE / NULLIF((SELECT SUM(PEER_REVENUE) FROM latest_revenue WHERE RN = 1), 0) as MARKET_SHARE_EST
FROM latest_revenue lr
LEFT JOIN quarry_counts qc
    ON (CASE
        WHEN lr.CIK = '0001396009' THEN 'VULCAN'
        WHEN lr.CIK = '0000916076' THEN 'MLM'
        WHEN lr.CIK = '0000849395' THEN 'CRH'
        WHEN lr.CIK = '0000918646' THEN 'EXP'
        WHEN lr.CIK = '0001571371' THEN 'SUM'
    END) = qc.OPERATOR_GROUP
WHERE lr.RN = 1
ORDER BY lr.PEER_REVENUE DESC NULLS LAST;

CREATE OR REPLACE VIEW VULCAN_MATERIALS_DB.ANALYTICS.COMPETITOR_REVENUE_TREND AS
SELECT
    cf.COMPANY_NAME, cf.CIK, cf.PERIOD_END_DATE, cf.FISCAL_YEAR, cf.FISCAL_PERIOD,
    cf.PEER_REVENUE, cf.PEER_OPERATING_INCOME, cf.PEER_MARGIN_EST, cf.PEER_REVENUE_QOQ,
    LAG(cf.PEER_REVENUE, 4) OVER (PARTITION BY cf.CIK ORDER BY cf.PERIOD_END_DATE) as PEER_REVENUE_4Q_AGO,
    CASE
        WHEN LAG(cf.PEER_REVENUE, 4) OVER (PARTITION BY cf.CIK ORDER BY cf.PERIOD_END_DATE) > 0
        THEN (cf.PEER_REVENUE - LAG(cf.PEER_REVENUE, 4) OVER (PARTITION BY cf.CIK ORDER BY cf.PERIOD_END_DATE))
             / LAG(cf.PEER_REVENUE, 4) OVER (PARTITION BY cf.CIK ORDER BY cf.PERIOD_END_DATE)
    END as PEER_REVENUE_YOY
FROM VULCAN_MATERIALS_DB.FEATURE_STORE."COMPETITOR_FEATURES$1" cf
WHERE cf.PEER_REVENUE IS NOT NULL
ORDER BY cf.CIK, cf.PERIOD_END_DATE;

CREATE OR REPLACE VIEW VULCAN_MATERIALS_DB.ANALYTICS.COPULA_VS_NAIVE_RISK AS
WITH latest_copula AS (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY MODEL_VERSION ORDER BY CREATED_AT DESC) as RN
    FROM VULCAN_MATERIALS_DB.ML.COPULA_PARAMETERS
)
SELECT
    mc.SCENARIO_ID,
    mc.NAIVE_P50 / 1e9 as NAIVE_P50_B, mc.NAIVE_P10 / 1e9 as NAIVE_P10_B,
    mc.NAIVE_VAR_95 / 1e9 as NAIVE_VAR_95_B, mc.NAIVE_CVAR_95 / 1e9 as NAIVE_CVAR_95_B,
    mc.NAIVE_PROB_MISS,
    mc.COPULA_P50 / 1e9 as COPULA_P50_B, mc.COPULA_P10 / 1e9 as COPULA_P10_B,
    mc.COPULA_VAR_95 / 1e9 as COPULA_VAR_95_B, mc.COPULA_CVAR_95 / 1e9 as COPULA_CVAR_95_B,
    mc.COPULA_PROB_MISS,
    mc.VAR_GAP_PCT, mc.CVAR_GAP_PCT, mc.N_PATHS, mc.N_MONTHS,
    cp.COPULA_TYPE, cp.N_OBSERVATIONS, cp.VARIABLES as COPULA_VARIABLES,
    mc.CREATED_AT
FROM VULCAN_MATERIALS_DB.ML.MODEL_COMPARISON mc
LEFT JOIN latest_copula cp
    ON CASE WHEN mc.SCENARIO_ID LIKE '%V2%' THEN 'v2' ELSE 'v1' END = cp.MODEL_VERSION
    AND cp.RN = 1
ORDER BY mc.CREATED_AT DESC;

CREATE OR REPLACE VIEW VULCAN_MATERIALS_DB.ANALYTICS.PRICING_OPPORTUNITY AS
SELECT
    op.REGION_CODE, op.PRODUCT_SEGMENT_CODE,
    ps.SEGMENT_NAME as PRODUCT_NAME,
    op.CURRENT_PRICE, op.OPTIMAL_PRICE,
    op.PRICE_DELTA_PCT * 100 as PRICE_DELTA_PCT,
    op.CURRENT_VOLUME, op.PREDICTED_VOLUME,
    op.VOLUME_DELTA_PCT * 100 as VOLUME_DELTA_PCT,
    op.CURRENT_PROFIT / 1e6 as CURRENT_PROFIT_M,
    op.OPTIMAL_PROFIT / 1e6 as OPTIMAL_PROFIT_M,
    op.PROFIT_DELTA / 1e6 as PROFIT_DELTA_M,
    op.PROFIT_DELTA_PCT * 100 as PROFIT_DELTA_PCT,
    op.BINDING_CONSTRAINTS, op.MARGIN_FLOOR_USED, op.PRICE_CHANGE_LIMIT,
    op.OPTIMIZER_STATUS,
    pe.OWN_ELASTICITY, pe.R_SQUARED as ELASTICITY_R_SQUARED,
    CASE WHEN ABS(pe.OWN_ELASTICITY) < 1 THEN 'INELASTIC (Pricing Power)' ELSE 'ELASTIC (Volume Risk)' END as ELASTICITY_CLASSIFICATION,
    op.MODEL_VERSION
FROM VULCAN_MATERIALS_DB.ML.OPTIMAL_PRICING op
LEFT JOIN VULCAN_MATERIALS_DB.ATOMIC.PRODUCT_SEGMENT ps ON op.PRODUCT_SEGMENT_CODE = ps.SEGMENT_CODE
LEFT JOIN (
    SELECT PRODUCT_SEGMENT_CODE, OWN_ELASTICITY, R_SQUARED,
           ROW_NUMBER() OVER (PARTITION BY PRODUCT_SEGMENT_CODE ORDER BY CREATED_AT DESC) as RN
    FROM VULCAN_MATERIALS_DB.ML.PRICE_ELASTICITY WHERE REGION_CODE = 'ALL'
) pe ON op.PRODUCT_SEGMENT_CODE = pe.PRODUCT_SEGMENT_CODE AND pe.RN = 1
WHERE op.MODEL_VERSION = (SELECT MAX(MODEL_VERSION) FROM VULCAN_MATERIALS_DB.ML.OPTIMAL_PRICING)
ORDER BY op.REGION_CODE, op.PRODUCT_SEGMENT_CODE;

CREATE OR REPLACE VIEW VULCAN_MATERIALS_DB.ANALYTICS.DEMAND_DRIVERS_PANEL AS
SELECT
    s.YEAR_MONTH, s.REGION_CODE, s.PRODUCT_SEGMENT_CODE,
    SUM(s.SHIPMENT_TONS) as TOTAL_VOLUME, SUM(s.REVENUE_USD) as TOTAL_REVENUE, AVG(s.PRICE_PER_TON) as AVG_PRICE,
    m.TOTAL_CONSTRUCTION_USD / 1e9 as CONSTRUCTION_SPEND_B,
    m.HIGHWAY_CONSTRUCTION_USD / 1e9 as HIGHWAY_SPEND_B,
    m.RESIDENTIAL_CONSTRUCTION_USD / 1e9 as RESIDENTIAL_SPEND_B,
    w.TEMP_AVG_F, w.PRECIP_TOTAL_IN, w.PRECIP_DAYS, w.N_WEATHER_DAYS as WEATHER_WORK_DAYS,
    e.ENERGY_PRICE_INDEX, pe.OWN_ELASTICITY, pe.R_SQUARED as ELASTICITY_R_SQUARED
FROM VULCAN_MATERIALS_DB.ATOMIC.MONTHLY_SHIPMENTS s
LEFT JOIN VULCAN_MATERIALS_DB.ATOMIC.MONTHLY_MACRO_INDICATORS m ON LAST_DAY(s.YEAR_MONTH) = m.YEAR_MONTH
LEFT JOIN VULCAN_MATERIALS_DB.ATOMIC.MONTHLY_WEATHER_BY_REGION w ON s.YEAR_MONTH = w.YEAR_MONTH AND s.REGION_CODE = w.REGION_CODE
LEFT JOIN VULCAN_MATERIALS_DB.ATOMIC.MONTHLY_ENERGY_PRICE_INDEX e ON LAST_DAY(s.YEAR_MONTH) = e.YEAR_MONTH
LEFT JOIN (
    SELECT PRODUCT_SEGMENT_CODE, OWN_ELASTICITY, R_SQUARED,
           ROW_NUMBER() OVER (PARTITION BY PRODUCT_SEGMENT_CODE ORDER BY CREATED_AT DESC) as RN
    FROM VULCAN_MATERIALS_DB.ML.PRICE_ELASTICITY WHERE REGION_CODE = 'ALL'
) pe ON s.PRODUCT_SEGMENT_CODE = pe.PRODUCT_SEGMENT_CODE AND pe.RN = 1
GROUP BY s.YEAR_MONTH, s.REGION_CODE, s.PRODUCT_SEGMENT_CODE,
         m.TOTAL_CONSTRUCTION_USD, m.HIGHWAY_CONSTRUCTION_USD, m.RESIDENTIAL_CONSTRUCTION_USD,
         w.TEMP_AVG_F, w.PRECIP_TOTAL_IN, w.PRECIP_DAYS, w.N_WEATHER_DAYS,
         e.ENERGY_PRICE_INDEX, pe.OWN_ELASTICITY, pe.R_SQUARED
ORDER BY s.YEAR_MONTH DESC, s.REGION_CODE, s.PRODUCT_SEGMENT_CODE;

CREATE OR REPLACE VIEW VULCAN_MATERIALS_DB.ANALYTICS.EARNINGS_SENTIMENT AS
SELECT
    t.COMPANY_NAME, t.CIK, t.PRIMARY_TICKER, t.FISCAL_PERIOD, t.FISCAL_YEAR,
    t.EVENT_TYPE, t.EVENT_TITLE, t.EVENT_TIMESTAMP,
    LENGTH(t.TRANSCRIPT_TEXT) as TRANSCRIPT_LENGTH,
    SNOWFLAKE.CORTEX.SENTIMENT(LEFT(t.TRANSCRIPT_TEXT, 10000)) as SENTIMENT_SCORE,
    SNOWFLAKE.CORTEX.SUMMARIZE(LEFT(t.TRANSCRIPT_TEXT, 10000)) as SUMMARY
FROM VULCAN_MATERIALS_DB.DOCS.COMPETITOR_EARNINGS_TRANSCRIPTS t
WHERE t.TRANSCRIPT_TEXT IS NOT NULL;

CREATE OR REPLACE VIEW VULCAN_MATERIALS_DB.ANALYTICS.QUARRY_COMPETITIVE_MAP AS
SELECT
    q.MINE_ID, q.MINE_NAME, q.OPERATOR_NAME, q.OPERATOR_GROUP,
    q.STATE, q.COUNTY, q.LATITUDE, q.LONGITUDE, q.REGION_CODE,
    q.PRIMARY_SIC, q.PRIMARY_CANVASS, q.NO_EMPLOYEES, q.NEAREST_TOWN,
    CASE
        WHEN q.OPERATOR_GROUP = 'VULCAN' THEN 'SnowCore Materials'
        WHEN q.OPERATOR_GROUP = 'MLM' THEN 'Martin Marietta'
        WHEN q.OPERATOR_GROUP = 'CRH' THEN 'CRH / Oldcastle'
        WHEN q.OPERATOR_GROUP = 'HEIDELBERG' THEN 'Heidelberg Materials'
        WHEN q.OPERATOR_GROUP = 'EXP' THEN 'Eagle Materials'
        WHEN q.OPERATOR_GROUP = 'SUM' THEN 'Summit Materials'
        WHEN q.OPERATOR_GROUP = 'ROGERS' THEN 'Rogers Group'
        WHEN q.OPERATOR_GROUP = 'KNIFE_RIVER' THEN 'Knife River'
        WHEN q.OPERATOR_GROUP = 'GRANITE_CONSTR' THEN 'Granite Construction'
        WHEN q.OPERATOR_GROUP = 'CEMEX' THEN 'CEMEX'
        ELSE 'Other'
    END as OPERATOR_DISPLAY_NAME,
    CASE WHEN q.OPERATOR_GROUP = 'VULCAN' THEN TRUE ELSE FALSE END as IS_SNOWCORE,
    q.MINE_STATUS
FROM VULCAN_MATERIALS_DB.ATOMIC.MSHA_QUARRY_SITES q;
